2022-11-06 17:10:49,254 INFO    StreamThr :21528 [internal.py:wandb_internal():88] W&B internal server running at pid: 21528, started at: 2022-11-06 17:10:49.246947
2022-11-06 17:10:49,256 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: status
2022-11-06 17:10:49,257 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: status
2022-11-06 17:10:49,259 INFO    WriterThread:21528 [datastore.py:open_for_write():75] open: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\run-z3vurjh9.wandb
2022-11-06 17:10:49,259 DEBUG   SenderThread:21528 [sender.py:send():303] send: header
2022-11-06 17:10:49,259 DEBUG   SenderThread:21528 [sender.py:send():303] send: run
2022-11-06 17:10:52,368 INFO    SenderThread:21528 [dir_watcher.py:__init__():216] watching files in: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files
2022-11-06 17:10:52,368 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: check_version
2022-11-06 17:10:52,368 INFO    SenderThread:21528 [sender.py:_start_run_threads():928] run started: z3vurjh9 with start time 1667754648.301947
2022-11-06 17:10:52,369 DEBUG   SenderThread:21528 [sender.py:send():303] send: summary
2022-11-06 17:10:52,369 INFO    SenderThread:21528 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-06 17:10:52,369 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: check_version
2022-11-06 17:10:53,385 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\wandb-summary.json
2022-11-06 17:10:57,388 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: run_start
2022-11-06 17:10:57,440 DEBUG   HandlerThread:21528 [meta.py:__init__():34] meta init
2022-11-06 17:10:57,440 DEBUG   HandlerThread:21528 [meta.py:__init__():49] meta init done
2022-11-06 17:10:57,440 DEBUG   HandlerThread:21528 [meta.py:probe():215] probe
2022-11-06 17:10:58,266 DEBUG   HandlerThread:21528 [meta.py:_setup_git():205] setup git
2022-11-06 17:10:58,343 DEBUG   HandlerThread:21528 [meta.py:_setup_git():212] setup git done
2022-11-06 17:10:58,343 DEBUG   HandlerThread:21528 [meta.py:_save_pip():53] save pip
2022-11-06 17:10:58,367 DEBUG   HandlerThread:21528 [meta.py:_save_pip():67] save pip done
2022-11-06 17:10:58,396 DEBUG   HandlerThread:21528 [meta.py:_save_conda():74] save conda
2022-11-06 17:10:58,440 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\conda-environment.yaml
2022-11-06 17:10:58,441 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\requirements.txt
2022-11-06 17:11:23,693 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\conda-environment.yaml
2022-11-06 17:11:23,925 DEBUG   HandlerThread:21528 [meta.py:_save_conda():84] save conda done
2022-11-06 17:11:23,925 DEBUG   HandlerThread:21528 [meta.py:probe():253] probe done
2022-11-06 17:11:23,926 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:11:23,926 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: stop_status
2022-11-06 17:11:23,929 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: pause
2022-11-06 17:11:23,929 INFO    HandlerThread:21528 [handler.py:handle_request_pause():696] stopping system metrics thread
2022-11-06 17:11:23,959 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:11:23,959 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: resume
2022-11-06 17:11:23,959 INFO    HandlerThread:21528 [handler.py:handle_request_resume():687] starting system metrics thread
2022-11-06 17:11:23,960 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: partial_history
2022-11-06 17:11:24,706 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\wandb-metadata.json
2022-11-06 17:11:34,287 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: log_artifact
2022-11-06 17:11:34,337 DEBUG   SenderThread:21528 [sender.py:send():303] send: telemetry
2022-11-06 17:11:34,338 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: stop_status
2022-11-06 17:11:34,344 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: partial_history
2022-11-06 17:11:34,838 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table\confusion_matrix_1_772153e07ee3f971e5c7.table.json
2022-11-06 17:11:34,839 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table
2022-11-06 17:11:34,839 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media
2022-11-06 17:11:37,785 DEBUG   SenderThread:21528 [sender.py:send():303] send: history
2022-11-06 17:11:37,785 DEBUG   SenderThread:21528 [sender.py:send():303] send: summary
2022-11-06 17:11:37,786 INFO    SenderThread:21528 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-06 17:11:37,787 DEBUG   SenderThread:21528 [sender.py:send():303] send: config
2022-11-06 17:11:37,787 DEBUG   SenderThread:21528 [sender.py:send():303] send: files
2022-11-06 17:11:37,787 INFO    SenderThread:21528 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-11-06 17:11:37,788 DEBUG   SenderThread:21528 [sender.py:send():303] send: stats
2022-11-06 17:11:37,788 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: log_artifact
2022-11-06 17:11:37,870 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\wandb-summary.json
2022-11-06 17:11:37,871 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\output.log
2022-11-06 17:11:39,894 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\output.log
2022-11-06 17:11:42,436 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:11:52,005 INFO    Thread-198:21528 [upload_job.py:push():143] Uploaded file C:\Users\mk-armah\AppData\Local\Temp\tmpwp9h5rr1wandb\3gecpho1-wandb-metadata.json
2022-11-06 17:12:01,200 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: log_artifact
2022-11-06 17:12:01,263 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: partial_history
2022-11-06 17:12:02,125 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table\summary_metrics_2_2abcc988595ece9eb69f.table.json
2022-11-06 17:12:02,126 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table
2022-11-06 17:12:02,454 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:12:04,509 INFO    Thread-200:21528 [upload_job.py:push():101] Uploaded file C:\Users\mk-armah\.cache\wandb\artifacts\obj\md5\42\cc1d37e5c4ffcb3233e3983dd875f3
2022-11-06 17:12:20,624 ERROR   Thread-190:21528 [internal_api.py:upload_file():1884] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/mk-armah/wsn-intrusion-detection/z3vurjh9/artifact/274485647/wandb_manifest.json?Expires=1667841125&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=A94wkj06zjiaPjXUkvMiU7MBrQ4mn3sDNR70%2BKfwJnKckwUmo%2B0BzvaX4QnGZxUzhABrZGEpBue3iW%2B9ptVJkOKF68ZMCZaRTj9i71i6rHVR1clXDQDAAzvWDdC4UBKTNRFuIK32fkXR%2BK42CybR4DWn05pBuPXKbCJaPcu%2F0CVhU6uEvVSzWM2sEGBMVJ9iKb8IbzKekn%2FBugv0QMsd2SSI%2FQwiIOk4m%2FujeaKuLP6fux3M%2FNsNP7LIBj5CkvlG5GEtsuQ5PRhfs9vDg0glZBHP7qTQx1fkpEJzfDzzexDvF5yxC87CByOLUu3B33UbuZWkYoy7c45t7qOKIy52jw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/mk-armah/wsn-intrusion-detection/z3vurjh9/artifact/274485647/wandb_manifest.json?Expires=1667841125&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=A94wkj06zjiaPjXUkvMiU7MBrQ4mn3sDNR70%2BKfwJnKckwUmo%2B0BzvaX4QnGZxUzhABrZGEpBue3iW%2B9ptVJkOKF68ZMCZaRTj9i71i6rHVR1clXDQDAAzvWDdC4UBKTNRFuIK32fkXR%2BK42CybR4DWn05pBuPXKbCJaPcu%2F0CVhU6uEvVSzWM2sEGBMVJ9iKb8IbzKekn%2FBugv0QMsd2SSI%2FQwiIOk4m%2FujeaKuLP6fux3M%2FNsNP7LIBj5CkvlG5GEtsuQ5PRhfs9vDg0glZBHP7qTQx1fkpEJzfDzzexDvF5yxC87CByOLUu3B33UbuZWkYoy7c45t7qOKIy52jw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D0475D94C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-11-06 17:12:20,624 ERROR   Thread-190:21528 [internal_api.py:upload_file():1886] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U43StpEYwb/h4Fp4CyaL3A==', 'Content-Length': '357'}
2022-11-06 17:12:20,624 ERROR   Thread-190:21528 [internal_api.py:upload_file():1888] upload_file response body: 
2022-11-06 17:12:22,464 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:12:24,158 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: log_artifact
2022-11-06 17:12:24,184 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: partial_history
2022-11-06 17:12:24,380 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table\class_proportions_3_618160970ffa30a4f2b1.table.json
2022-11-06 17:12:24,381 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table
2022-11-06 17:12:31,145 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: log_artifact
2022-11-06 17:12:31,171 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: partial_history
2022-11-06 17:12:31,456 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table\roc_4_6aebb123c7c530adf3b3.table.json
2022-11-06 17:12:31,456 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table
2022-11-06 17:12:32,428 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: log_artifact
2022-11-06 17:12:32,443 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: partial_history
2022-11-06 17:12:32,445 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: pause
2022-11-06 17:12:32,445 INFO    HandlerThread:21528 [handler.py:handle_request_pause():696] stopping system metrics thread
2022-11-06 17:12:32,462 INFO    Thread-191:21528 [dir_watcher.py:_on_file_created():275] file/dir created: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table\precision_recall_5_9ab90d419e061a194755.table.json
2022-11-06 17:12:32,463 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\media\table
2022-11-06 17:12:33,413 ERROR   Thread-190:21528 [internal_api.py:upload_file():1884] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/mk-armah/wsn-intrusion-detection/z3vurjh9/artifact/274485647/wandb_manifest.json?Expires=1667841125&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=A94wkj06zjiaPjXUkvMiU7MBrQ4mn3sDNR70%2BKfwJnKckwUmo%2B0BzvaX4QnGZxUzhABrZGEpBue3iW%2B9ptVJkOKF68ZMCZaRTj9i71i6rHVR1clXDQDAAzvWDdC4UBKTNRFuIK32fkXR%2BK42CybR4DWn05pBuPXKbCJaPcu%2F0CVhU6uEvVSzWM2sEGBMVJ9iKb8IbzKekn%2FBugv0QMsd2SSI%2FQwiIOk4m%2FujeaKuLP6fux3M%2FNsNP7LIBj5CkvlG5GEtsuQ5PRhfs9vDg0glZBHP7qTQx1fkpEJzfDzzexDvF5yxC87CByOLUu3B33UbuZWkYoy7c45t7qOKIy52jw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/mk-armah/wsn-intrusion-detection/z3vurjh9/artifact/274485647/wandb_manifest.json?Expires=1667841125&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=A94wkj06zjiaPjXUkvMiU7MBrQ4mn3sDNR70%2BKfwJnKckwUmo%2B0BzvaX4QnGZxUzhABrZGEpBue3iW%2B9ptVJkOKF68ZMCZaRTj9i71i6rHVR1clXDQDAAzvWDdC4UBKTNRFuIK32fkXR%2BK42CybR4DWn05pBuPXKbCJaPcu%2F0CVhU6uEvVSzWM2sEGBMVJ9iKb8IbzKekn%2FBugv0QMsd2SSI%2FQwiIOk4m%2FujeaKuLP6fux3M%2FNsNP7LIBj5CkvlG5GEtsuQ5PRhfs9vDg0glZBHP7qTQx1fkpEJzfDzzexDvF5yxC87CByOLUu3B33UbuZWkYoy7c45t7qOKIy52jw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D04975E610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-11-06 17:12:33,413 ERROR   Thread-190:21528 [internal_api.py:upload_file():1886] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U43StpEYwb/h4Fp4CyaL3A==', 'Content-Length': '357'}
2022-11-06 17:12:33,413 ERROR   Thread-190:21528 [internal_api.py:upload_file():1888] upload_file response body: 
2022-11-06 17:12:37,310 INFO    SenderThread:21528 [sender.py:send_request_log_artifact():1222] logged artifact run-z3vurjh9-confusion_matrix - {'id': 'QXJ0aWZhY3Q6Mjc0NDg1NjQ3', 'digest': '700cdb8696f4a68597265dbbe3b8cf1e', 'state': 'PENDING', 'aliases': [], 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQ0NDE2OTMx', 'latestArtifact': None}, 'version': 'latest'}
2022-11-06 17:12:37,768 DEBUG   SenderThread:21528 [sender.py:send():303] send: files
2022-11-06 17:12:37,768 INFO    SenderThread:21528 [sender.py:_save_file():1171] saving file media\table\confusion_matrix_1_772153e07ee3f971e5c7.table.json with policy now
2022-11-06 17:12:37,769 DEBUG   SenderThread:21528 [sender.py:send():303] send: history
2022-11-06 17:12:37,769 DEBUG   SenderThread:21528 [sender.py:send():303] send: summary
2022-11-06 17:12:37,771 INFO    SenderThread:21528 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-06 17:12:37,772 DEBUG   SenderThread:21528 [sender.py:send():303] send: config
2022-11-06 17:12:37,772 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: stop_status
2022-11-06 17:12:38,228 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: log_artifact
2022-11-06 17:12:38,546 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\wandb-summary.json
2022-11-06 17:12:38,547 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\config.yaml
2022-11-06 17:12:39,138 INFO    Thread-201:21528 [upload_job.py:push():143] Uploaded file C:\Users\mk-armah\AppData\Local\Temp\tmpwp9h5rr1wandb\1ahv4awt-media/table/confusion_matrix_1_772153e07ee3f971e5c7.table.json
2022-11-06 17:12:40,549 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\output.log
2022-11-06 17:12:41,610 INFO    Thread-203:21528 [upload_job.py:push():101] Uploaded file C:\Users\mk-armah\.cache\wandb\artifacts\obj\md5\c7\eba30ab0ab1bc0b0cda838a8c28f7e
2022-11-06 17:12:42,468 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:12:44,549 INFO    SenderThread:21528 [sender.py:send_request_log_artifact():1222] logged artifact run-z3vurjh9-summary_metrics - {'id': 'QXJ0aWZhY3Q6Mjc0NDg2MTE0', 'digest': '3bf16e5dccdddbd763f9668a64cbbb41', 'state': 'PENDING', 'aliases': [], 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQ0NDE2OTY3', 'latestArtifact': None}, 'version': 'latest'}
2022-11-06 17:12:44,550 DEBUG   SenderThread:21528 [sender.py:send():303] send: files
2022-11-06 17:12:44,550 INFO    SenderThread:21528 [sender.py:_save_file():1171] saving file media\table\summary_metrics_2_2abcc988595ece9eb69f.table.json with policy now
2022-11-06 17:12:44,551 DEBUG   SenderThread:21528 [sender.py:send():303] send: history
2022-11-06 17:12:44,551 DEBUG   SenderThread:21528 [sender.py:send():303] send: summary
2022-11-06 17:12:44,552 INFO    SenderThread:21528 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-06 17:12:44,552 DEBUG   SenderThread:21528 [sender.py:send():303] send: config
2022-11-06 17:12:44,552 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: stop_status
2022-11-06 17:12:44,587 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\wandb-summary.json
2022-11-06 17:12:45,030 DEBUG   SenderThread:21528 [sender.py:send():303] send: stats
2022-11-06 17:12:45,030 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: stop_status
2022-11-06 17:12:45,661 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: log_artifact
2022-11-06 17:12:46,014 INFO    Thread-204:21528 [upload_job.py:push():143] Uploaded file C:\Users\mk-armah\AppData\Local\Temp\tmpwp9h5rr1wandb\3rc9m8mu-media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json
2022-11-06 17:12:46,610 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\output.log
2022-11-06 17:13:02,486 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:13:10,043 INFO    Thread-206:21528 [upload_job.py:push():101] Uploaded file C:\Users\mk-armah\.cache\wandb\artifacts\obj\md5\eb\48735f5820a7250053cee856e84574
2022-11-06 17:13:12,422 INFO    SenderThread:21528 [sender.py:send_request_log_artifact():1222] logged artifact run-z3vurjh9-class_proportions - {'id': 'QXJ0aWZhY3Q6Mjc0NDg2MTg3', 'digest': '138de8b087b5970c53d0a9cab2cb1984', 'state': 'PENDING', 'aliases': [], 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQ0NDE2OTc5', 'latestArtifact': None}, 'version': 'latest'}
2022-11-06 17:13:12,904 DEBUG   SenderThread:21528 [sender.py:send():303] send: files
2022-11-06 17:13:12,904 INFO    SenderThread:21528 [sender.py:_save_file():1171] saving file media\table\class_proportions_3_618160970ffa30a4f2b1.table.json with policy now
2022-11-06 17:13:12,905 DEBUG   SenderThread:21528 [sender.py:send():303] send: history
2022-11-06 17:13:12,905 DEBUG   SenderThread:21528 [sender.py:send():303] send: summary
2022-11-06 17:13:12,906 INFO    SenderThread:21528 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-06 17:13:12,906 DEBUG   SenderThread:21528 [sender.py:send():303] send: telemetry
2022-11-06 17:13:12,906 DEBUG   SenderThread:21528 [sender.py:send():303] send: config
2022-11-06 17:13:12,906 DEBUG   SenderThread:21528 [sender.py:send_request():317] send_request: log_artifact
2022-11-06 17:13:13,888 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\wandb-summary.json
2022-11-06 17:13:13,888 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\config.yaml
2022-11-06 17:13:14,897 INFO    Thread-191:21528 [dir_watcher.py:_on_file_modified():292] file/dir modified: D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\files\output.log
2022-11-06 17:13:22,506 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:13:23,952 ERROR   SenderThread:21528 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\Users\mk-armah\miniconda3\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D0497842B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D0497842B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\wandb\sdk\lib\retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Users\mk-armah\miniconda3\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D0497842B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-11-06 17:13:42,521 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:14:02,530 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:14:18,108 WARNING FileStreamThread:21528 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)). func: <bound method Session.post of <requests.sessions.Session object at 0x000001D04976EA90>>, args: ('https://api.wandb.ai/files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"feature_importances": null, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2, "confusion_matrix": {"_type": "table-file", "sha256": "772153e07ee3f971e5c7c2dba28f31bc4b7d5375a804f8464c53d5fdf2b5c1a9", "size": 758, "artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "_latest_artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "path": "media/table/confusion_matrix_1_772153e07ee3f971e5c7.table.json", "ncols": 3, "nrows": 25}, "summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}}']}, 'wandb-history.jsonl': {'offset': 2, 'content': ['{"summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://a6h86fdlrplpvo55jmd0d5qi0wr11s26d3434pxi0dxbk1uwekmtyb7i3jyw1jrxnjuednq5fz6ballyzk4giuzf7t7xykbstyet6dpwyo6h1gk86543svc71omccvju/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2}']}, 'wandb-events.jsonl': {'offset': 1, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.27, "system.gpu.0.temp": 59.0, "system.cpu": 28.52, "system.memory": 91.15, "system.disk": 57.9, "system.proc.memory.availableMB": 709.14, "system.proc.memory.rssMB": 109.91, "system.proc.memory.percent": 1.37, "system.proc.cpu.threads": 44.0, "system.network.sent": 636807, "system.network.recv": 1125657, "_wandb": true, "_timestamp": 1667754723.062334, "_runtime": 74.760387}']}, 'output.log': {'offset': 4, 'content': ['ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged confusion matrix.\n', 'ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged summary metrics.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n']}}, 'dropped': 0}}
2022-11-06 17:14:20,481 WARNING FileStreamThread:21528 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D04A7664C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000001D04976EA90>>, args: ('https://api.wandb.ai/files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"feature_importances": null, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2, "confusion_matrix": {"_type": "table-file", "sha256": "772153e07ee3f971e5c7c2dba28f31bc4b7d5375a804f8464c53d5fdf2b5c1a9", "size": 758, "artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "_latest_artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "path": "media/table/confusion_matrix_1_772153e07ee3f971e5c7.table.json", "ncols": 3, "nrows": 25}, "summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}}']}, 'wandb-history.jsonl': {'offset': 2, 'content': ['{"summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://a6h86fdlrplpvo55jmd0d5qi0wr11s26d3434pxi0dxbk1uwekmtyb7i3jyw1jrxnjuednq5fz6ballyzk4giuzf7t7xykbstyet6dpwyo6h1gk86543svc71omccvju/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2}']}, 'wandb-events.jsonl': {'offset': 1, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.27, "system.gpu.0.temp": 59.0, "system.cpu": 28.52, "system.memory": 91.15, "system.disk": 57.9, "system.proc.memory.availableMB": 709.14, "system.proc.memory.rssMB": 109.91, "system.proc.memory.percent": 1.37, "system.proc.cpu.threads": 44.0, "system.network.sent": 636807, "system.network.recv": 1125657, "_wandb": true, "_timestamp": 1667754723.062334, "_runtime": 74.760387}']}, 'output.log': {'offset': 4, 'content': ['ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged confusion matrix.\n', 'ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged summary metrics.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n']}}, 'dropped': 0}}
2022-11-06 17:14:22,541 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:14:25,270 WARNING FileStreamThread:21528 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D04A7663D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000001D04976EA90>>, args: ('https://api.wandb.ai/files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"feature_importances": null, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2, "confusion_matrix": {"_type": "table-file", "sha256": "772153e07ee3f971e5c7c2dba28f31bc4b7d5375a804f8464c53d5fdf2b5c1a9", "size": 758, "artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "_latest_artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "path": "media/table/confusion_matrix_1_772153e07ee3f971e5c7.table.json", "ncols": 3, "nrows": 25}, "summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}}']}, 'wandb-history.jsonl': {'offset': 2, 'content': ['{"summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://a6h86fdlrplpvo55jmd0d5qi0wr11s26d3434pxi0dxbk1uwekmtyb7i3jyw1jrxnjuednq5fz6ballyzk4giuzf7t7xykbstyet6dpwyo6h1gk86543svc71omccvju/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2}']}, 'wandb-events.jsonl': {'offset': 1, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.27, "system.gpu.0.temp": 59.0, "system.cpu": 28.52, "system.memory": 91.15, "system.disk": 57.9, "system.proc.memory.availableMB": 709.14, "system.proc.memory.rssMB": 109.91, "system.proc.memory.percent": 1.37, "system.proc.cpu.threads": 44.0, "system.network.sent": 636807, "system.network.recv": 1125657, "_wandb": true, "_timestamp": 1667754723.062334, "_runtime": 74.760387}']}, 'output.log': {'offset': 4, 'content': ['ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged confusion matrix.\n', 'ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged summary metrics.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n']}}, 'dropped': 0}}
2022-11-06 17:14:34,221 WARNING FileStreamThread:21528 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D04A766100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000001D04976EA90>>, args: ('https://api.wandb.ai/files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"feature_importances": null, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2, "confusion_matrix": {"_type": "table-file", "sha256": "772153e07ee3f971e5c7c2dba28f31bc4b7d5375a804f8464c53d5fdf2b5c1a9", "size": 758, "artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "_latest_artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "path": "media/table/confusion_matrix_1_772153e07ee3f971e5c7.table.json", "ncols": 3, "nrows": 25}, "summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}}']}, 'wandb-history.jsonl': {'offset': 2, 'content': ['{"summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://a6h86fdlrplpvo55jmd0d5qi0wr11s26d3434pxi0dxbk1uwekmtyb7i3jyw1jrxnjuednq5fz6ballyzk4giuzf7t7xykbstyet6dpwyo6h1gk86543svc71omccvju/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2}']}, 'wandb-events.jsonl': {'offset': 1, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.27, "system.gpu.0.temp": 59.0, "system.cpu": 28.52, "system.memory": 91.15, "system.disk": 57.9, "system.proc.memory.availableMB": 709.14, "system.proc.memory.rssMB": 109.91, "system.proc.memory.percent": 1.37, "system.proc.cpu.threads": 44.0, "system.network.sent": 636807, "system.network.recv": 1125657, "_wandb": true, "_timestamp": 1667754723.062334, "_runtime": 74.760387}']}, 'output.log': {'offset': 4, 'content': ['ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged confusion matrix.\n', 'ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged summary metrics.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n']}}, 'dropped': 0}}
2022-11-06 17:14:42,565 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:14:53,570 WARNING FileStreamThread:21528 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D04A766160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000001D04976EA90>>, args: ('https://api.wandb.ai/files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"feature_importances": null, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2, "confusion_matrix": {"_type": "table-file", "sha256": "772153e07ee3f971e5c7c2dba28f31bc4b7d5375a804f8464c53d5fdf2b5c1a9", "size": 758, "artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "_latest_artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "path": "media/table/confusion_matrix_1_772153e07ee3f971e5c7.table.json", "ncols": 3, "nrows": 25}, "summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}}']}, 'wandb-history.jsonl': {'offset': 2, 'content': ['{"summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://a6h86fdlrplpvo55jmd0d5qi0wr11s26d3434pxi0dxbk1uwekmtyb7i3jyw1jrxnjuednq5fz6ballyzk4giuzf7t7xykbstyet6dpwyo6h1gk86543svc71omccvju/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2}']}, 'wandb-events.jsonl': {'offset': 1, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.27, "system.gpu.0.temp": 59.0, "system.cpu": 28.52, "system.memory": 91.15, "system.disk": 57.9, "system.proc.memory.availableMB": 709.14, "system.proc.memory.rssMB": 109.91, "system.proc.memory.percent": 1.37, "system.proc.cpu.threads": 44.0, "system.network.sent": 636807, "system.network.recv": 1125657, "_wandb": true, "_timestamp": 1667754723.062334, "_runtime": 74.760387}']}, 'output.log': {'offset': 4, 'content': ['ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged confusion matrix.\n', 'ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged summary metrics.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n']}}, 'dropped': 0}}
2022-11-06 17:15:02,576 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:15:22,587 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:15:32,673 WARNING FileStreamThread:21528 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D04A766880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000001D04976EA90>>, args: ('https://api.wandb.ai/files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"feature_importances": null, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2, "confusion_matrix": {"_type": "table-file", "sha256": "772153e07ee3f971e5c7c2dba28f31bc4b7d5375a804f8464c53d5fdf2b5c1a9", "size": 758, "artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "_latest_artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "path": "media/table/confusion_matrix_1_772153e07ee3f971e5c7.table.json", "ncols": 3, "nrows": 25}, "summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}}']}, 'wandb-history.jsonl': {'offset': 2, 'content': ['{"summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://a6h86fdlrplpvo55jmd0d5qi0wr11s26d3434pxi0dxbk1uwekmtyb7i3jyw1jrxnjuednq5fz6ballyzk4giuzf7t7xykbstyet6dpwyo6h1gk86543svc71omccvju/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2}']}, 'wandb-events.jsonl': {'offset': 1, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.27, "system.gpu.0.temp": 59.0, "system.cpu": 28.52, "system.memory": 91.15, "system.disk": 57.9, "system.proc.memory.availableMB": 709.14, "system.proc.memory.rssMB": 109.91, "system.proc.memory.percent": 1.37, "system.proc.cpu.threads": 44.0, "system.network.sent": 636807, "system.network.recv": 1125657, "_wandb": true, "_timestamp": 1667754723.062334, "_runtime": 74.760387}']}, 'output.log': {'offset': 4, 'content': ['ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged confusion matrix.\n', 'ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged summary metrics.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n']}}, 'dropped': 0}}
2022-11-06 17:15:42,609 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:16:02,627 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:16:22,641 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:16:42,655 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:16:49,291 WARNING FileStreamThread:21528 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D04A7689A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x000001D04976EA90>>, args: ('https://api.wandb.ai/files/mk-armah/wsn-intrusion-detection/z3vurjh9/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"feature_importances": null, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2, "confusion_matrix": {"_type": "table-file", "sha256": "772153e07ee3f971e5c7c2dba28f31bc4b7d5375a804f8464c53d5fdf2b5c1a9", "size": 758, "artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "_latest_artifact_path": "wandb-client-artifact://hdfk89o8kvntr82g7vhnissxw99w8qi9c6ow4lqxk2tdocl35cfccqzwhnh1sxwmtuxrglqw1m4jr6rv62ytteg5jiwa21jwrnu052so4vcz61tq3vl7fzuv1otcz0mm:latest/confusion_matrix.table.json", "path": "media/table/confusion_matrix_1_772153e07ee3f971e5c7.table.json", "ncols": 3, "nrows": 25}, "summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}}']}, 'wandb-history.jsonl': {'offset': 2, 'content': ['{"summary_metrics": {"_type": "table-file", "sha256": "2abcc988595ece9eb69f6cbca4c4cb14f17b86927ef3660bddd0d7e1359c4333", "size": 201, "artifact_path": "wandb-client-artifact://a6h86fdlrplpvo55jmd0d5qi0wr11s26d3434pxi0dxbk1uwekmtyb7i3jyw1jrxnjuednq5fz6ballyzk4giuzf7t7xykbstyet6dpwyo6h1gk86543svc71omccvju/summary_metrics.table.json", "_latest_artifact_path": "wandb-client-artifact://nq8t3sbmpejupg2wzrf40d274azvrmtf5b5escl7epl736ivv9m530xr3658dacjb2hy33qcx249pn1ujc57gz5189ocmmo7tun4iyyitksgta6bjq8b4fo7d0ucempg:latest/summary_metrics.table.json", "path": "media/table/summary_metrics_2_2abcc988595ece9eb69f.table.json", "ncols": 3, "nrows": 4}, "_timestamp": 1667754721.2613368, "_runtime": 72.95938968658447, "_step": 2}']}, 'wandb-events.jsonl': {'offset': 1, 'content': ['{"system.gpu.0.gpu": 0.0, "system.gpu.0.memory": 0.0, "system.gpu.0.memoryAllocated": 3.27, "system.gpu.0.temp": 59.0, "system.cpu": 28.52, "system.memory": 91.15, "system.disk": 57.9, "system.proc.memory.availableMB": 709.14, "system.proc.memory.rssMB": 109.91, "system.proc.memory.percent": 1.37, "system.proc.cpu.threads": 44.0, "system.network.sent": 636807, "system.network.recv": 1125657, "_wandb": true, "_timestamp": 1667754723.062334, "_runtime": 74.760387}']}, 'output.log': {'offset': 4, 'content': ['ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged confusion matrix.\n', 'ERROR 2022-11-06T17:12:40.121456 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Logged summary metrics.\n', 'ERROR 2022-11-06T17:12:46.156487 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: \x1b[33mWARNING\x1b[39m A graphql request initiated by the public wandb API timed out (timeout=9 sec). Create a new API with an integer timeout larger than 9, e.g., `api = wandb.Api(timeout=19)` to increase the graphql timeout.\n']}}, 'dropped': 0}}
2022-11-06 17:17:02,660 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:17:22,675 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:17:42,697 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
2022-11-06 17:18:02,716 DEBUG   HandlerThread:21528 [handler.py:handle_request():138] handle_request: stop_status
