2022-11-06 17:09:52,074 INFO    MainThread:16796 [wandb_setup.py:_flush():68] Configure stats pid to 16796
2022-11-06 17:09:52,094 INFO    MainThread:16796 [wandb_setup.py:_flush():68] Loading settings from C:\Users\mk-armah\.config\wandb\settings
2022-11-06 17:09:52,094 INFO    MainThread:16796 [wandb_setup.py:_flush():68] Loading settings from D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\settings
2022-11-06 17:09:52,094 INFO    MainThread:16796 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-06 17:09:52,095 INFO    MainThread:16796 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-06 17:09:52,095 INFO    MainThread:16796 [wandb_setup.py:_flush():68] Applying login settings: {'force': True}
2022-11-06 17:09:52,096 INFO    MainThread:16796 [wandb_init.py:_log_setup():476] Logging user logs to D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\logs\debug.log
2022-11-06 17:09:52,096 INFO    MainThread:16796 [wandb_init.py:_log_setup():477] Logging internal logs to D:\Users\mk-armah\OneDrive\VS-CODE\PYTHON\WSN-Intrusion-Detection\wandb\run-20221106_170952-z3vurjh9\logs\debug-internal.log
2022-11-06 17:09:52,098 INFO    MainThread:16796 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001C616EDE3A0>
2022-11-06 17:09:52,141 INFO    MainThread:16796 [wandb_init.py:init():516] calling init triggers
2022-11-06 17:09:52,141 INFO    MainThread:16796 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-06 17:09:52,142 INFO    MainThread:16796 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 1z7it3ab
2022-11-06 17:09:52,148 INFO    MainThread:16796 [wandb_run.py:_finish():1746] finishing run mk-armah/wsn-intrusion-detection/1z7it3ab
2022-11-06 17:09:52,150 INFO    MainThread:16796 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-11-06 17:09:52,153 INFO    MainThread:16796 [wandb_run.py:_restore():1932] restore
2022-11-06 17:09:52,154 INFO    MainThread:16796 [wandb_run.py:_restore():1938] restore done
2022-11-06 17:10:48,235 INFO    MainThread:16796 [wandb_run.py:_footer_history_summary_info():3377] rendering history
2022-11-06 17:10:48,236 INFO    MainThread:16796 [wandb_run.py:_footer_history_summary_info():3409] rendering summary
2022-11-06 17:10:48,267 INFO    MainThread:16796 [wandb_run.py:_footer_sync_info():3333] logging synced files
2022-11-06 17:10:48,280 INFO    MainThread:16796 [wandb_init.py:init():569] starting backend
2022-11-06 17:10:48,281 INFO    MainThread:16796 [wandb_init.py:init():573] setting up manager
2022-11-06 17:10:48,290 INFO    MainThread:16796 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-11-06 17:10:48,297 INFO    MainThread:16796 [wandb_init.py:init():580] backend started and connected
2022-11-06 17:10:48,471 INFO    MainThread:16796 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2022-11-06 17:10:48,541 INFO    MainThread:16796 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 15544617: character maps to <undefined>
2022-11-06 17:10:48,543 INFO    MainThread:16796 [wandb_init.py:init():658] updated telemetry
2022-11-06 17:10:48,745 INFO    MainThread:16796 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-06 17:10:52,367 INFO    MainThread:16796 [wandb_run.py:_on_init():2000] communicating current version
2022-11-06 17:10:57,380 INFO    MainThread:16796 [wandb_run.py:_on_init():2004] got version response None
2022-11-06 17:10:57,380 INFO    MainThread:16796 [wandb_init.py:init():728] starting run threads in backend
2022-11-06 17:11:02,407 INFO    MainThread:16796 [wandb_run.py:_console_start():1980] atexit reg
2022-11-06 17:11:02,408 INFO    MainThread:16796 [wandb_run.py:_redirect():1838] redirect: SettingsConsole.WRAP_RAW
2022-11-06 17:11:02,408 INFO    MainThread:16796 [wandb_run.py:_redirect():1903] Wrapping output streams.
2022-11-06 17:11:02,408 INFO    MainThread:16796 [wandb_run.py:_redirect():1925] Redirects installed.
2022-11-06 17:11:02,410 INFO    MainThread:16796 [wandb_init.py:init():765] run started, returning control to user process
2022-11-06 17:11:02,417 INFO    MainThread:16796 [wandb_init.py:_pause_backend():389] pausing backend
2022-11-06 17:11:02,418 INFO    MainThread:16796 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2022-11-06 17:11:23,098 INFO    MainThread:16796 [wandb_init.py:_resume_backend():398] resuming backend
2022-11-06 17:11:23,625 INFO    MainThread:16796 [wandb_run.py:_config_callback():1160] config_cb ('_wandb', 'viz', 'confusion_matrix') {'id': 'wandb/confusion_matrix/v1', 'historyFieldSettings': {'x-axis': '_step', 'key': 'confusion_matrix'}} None
2022-11-06 17:11:38,453 INFO    MainThread:16796 [wandb_run.py:_config_callback():1160] config_cb ('_wandb', 'viz', 'summary_metrics') {'id': 'wandb/metrics/v1', 'historyFieldSettings': {'x-axis': '_step', 'key': 'summary_metrics'}} None
2022-11-06 17:12:01,988 INFO    MainThread:16796 [wandb_run.py:_config_callback():1160] config_cb ('_wandb', 'viz', 'class_proportions') {'id': 'wandb/class_proportions/v1', 'historyFieldSettings': {'x-axis': '_step', 'key': 'class_proportions'}} None
2022-11-06 17:12:27,285 INFO    MainThread:16796 [wandb_run.py:_config_callback():1160] config_cb ('_wandb', 'viz', 'roc') {'id': 'wandb/roc/v1', 'historyFieldSettings': {'x-axis': '_step', 'key': 'roc'}} None
2022-11-06 17:12:31,899 INFO    MainThread:16796 [wandb_run.py:_config_callback():1160] config_cb ('_wandb', 'viz', 'precision_recall') {'id': 'wandb/pr_curve/v1', 'historyFieldSettings': {'x-axis': '_step', 'key': 'precision_recall'}} None
2022-11-06 17:12:32,445 INFO    MainThread:16796 [wandb_init.py:_pause_backend():389] pausing backend
2022-11-06 17:12:32,445 INFO    MainThread:16796 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2022-11-06 17:18:14,284 WARNING MsgRouterThr:16796 [router.py:message_loop():77] message_loop has been closed
